# Meta

title:         "Bulma: a modern CSS framework based on Flexbox"
description:   "Bulma is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."
env:           "production"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://bulma.io
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/jgthms/bulma/releases/download/0.6.0/bulma-0.6.0.zip
github:        https://github.com/jgthms/bulma
twitter:       https://twitter.com/jgthms
version:       0.6.0
vernum:        60
