# Meta

title:         "Bulma: a modern CSS framework based on Flexbox"
description:   "Bulma is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."
env:           "production"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://bulma.io
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/jgthms/bulma/releases/download/0.6.2/bulma-0.6.2.zip
github:        https://github.com/jgthms/bulma
twitter:       https://twitter.com/jgthms
version:       0.6.2
